# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoViewApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoViewApp

    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'SVProgressHUD'

  target 'PhotoViewAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoViewAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
